---

- name: add system groups
  group:
    name: "{{ item }}"
    state: present
    system: yes
  with_items:
    - nopwdsudo
    - sshlogin

- name: add initial groups
  group:
    name: "{{ item }}"
    state: present
    system: yes
  with_items:
  - initial_groups

- name: create base user group
  group:
    name: "{{ base_user_name }}"
    state: present

- name: create base user
  user:
    name: "{{ base_user_name }}"
    createhome: yes
    home: "{{ base_user_home }}"
    generate_ssh_key: no
    group: "{{ base_user_name }}"
    groups: "nopwdsudo,sshlogin"
    state: present

- name: generate random password for base user
  command: "/usr/bin/openssl rand -base64 32 | passwd --stdin {{ base_user_name }}"
  when: random_passwords|bool

- name: setup base user ssh
  file:
    state: directory
    dest: "{{ base_user_home }}/.ssh"
    mode: 0700
    owner: "{{ base_user_name }}"
    group: "{{ base_user_name }}"


- name: create initial users
  user:
    name: "{{ item['name'] }}"
    createhome: yes
    home: "{{ item['home'] }}"
    generate_ssh_key: no
    group: # primary group
    groups: # additional groups
    state: present
  register: "user_{{ item['name'] }}"
  with_items: initial_users

- name: generate random password for initial users
  command: "/usr/bin/openssl rand -base64 32 | passwd --stdin {{ item['name'] }}"
  with_items: initial_users
  when: "user_{{ item['name'] }}.changed or force_password_update|bool"

- name: setup ssh for new users
  file:
    status: directory
    dest: "{{ item.home }}/.ssh"
    mode: 0700
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: initial_users
