---

- name: ensure localhost is defined in hosts
  lineinfile: >
    dest="/etc/hosts"
    regexp="^127\.0\.0\.1\s+localhost"
    line="127.0.0.1   localhost"
    state=present
    owner=root
    group=root
    mode=0644

- name: add inventory hostname to hosts file
  lineinfile: >
    dest="/etc/hosts"
    regexp="^127\.0\.0\.1\s+{{ inventory_hostname }}"
    line="127.0.0.1   {{ inventory_hostname }}  # ansible managed"
    state=present
    owner=root
    group=root
    mode=0644
  when: inventory_hostname is defined

- name: additional entries for the hosts file
  lineinfile: >
    dest="/etc/hosts"
    regexp="^{{ item.address }}\s+{{ item.host }}"
    line="{{ item.address }}   {{ item.host }}  # ansible managed"
    state=present
    owner=root
    group=root
    mode=0644
  with_items: extra_hosts
