---

- name: ensure localhost is defined in hosts
  lineinfile: >
    dest="/etc/hosts"
    regexp="^127\.0\.0\.1\s+localhost"
    line="127.0.0.1   localhost"
    state=present
    owner=root
    group=root
    mode=0644

- name: add current hostname to hosts file
  lineinfile: >
    dest="/etc/hosts"
    regexp="^127\.0\.0\.1\s+{{ inventory_hostname }}"
    line="127.0.0.1   {{ inventory_hostname }}  # ansible managed"
    state=present
    owner=root
    group=root
    mode=0644
  when: inventory_hostname is defined
