---

# install system ugrades and reboot if necessary
- include: system-upgrade.yml

# ensure certain entries are present in /etc/hosts
- include: hostsfile.yml

# install fail2ban with default config
- include: fail2ban.yml

# create system groups for sudo access
- include: system-groups.yml

# create a non-root 'default' user
- include: base_user.yml
