---

# https://realguess.net/2014/12/21/ansible-update-servers-to-the-latest-and-reboot/
# https://coderwall.com/p/0nckqg/ansible-reboot-ubuntu-if-needed
# sudo shutdown -h now  # <-- safe reboot
- name: check if upgrades are available
  command: /usr/lib/update-notifier/apt-check --package-names
  register: upgrades
  changed_when: upgrades.stderr != ""
  when: dist_upgrade|bool

- name: update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist
  when: upgrades is defined and upgrades.stderr != ""
  register: upgraded

- name: reboot server to apply updates
  command: "shutdown -r now '{{ reboot_comment }}'"
  args:
    removes: /var/run/reboot-required
  sudo: yes
  register: rebooting
  when: upgraded|changed
  #async: 0
  #poll: 0
  #ignore_errors: true

# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
- name: wait for server to reboot
  local_action:
    module: wait_for
    #host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    host: "{{ inventory_hostname|default(ansible_ssh_host) }}"
    port: "{{ reboot_ssh_port }}"
    state: started
    delay: 15
    connect_timeout: 15
    timeout: 300
  sudo: false
  when: rebooting|changed
